services:
  mongo:
    image: mongo:7
    container_name: bulkcart-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: bulkcart-backend
    restart: always
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017/bulkcart_dev
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: bulkcart-frontend
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo_data:
